CLR P1.0
MOV TMOD, #01h
MOV R2, #20
DELAY: 	MOV TH0, #048h
	            MOV TL0, #0FDH
	   	CPL P1.0
	   	SJMP DELAY
	   	SETB TR0
HERE:	JNB TF0, HERE
		DJNZ R2, DELAY
		CLR TR0
		CLR TF0
